# Generated by Django 3.1.7 on 2021-04-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0003_auto_20210410_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Report',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phoneno',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
