# Generated by Django 3.1.7 on 2021-04-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0004_auto_20210410_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=122, null=True)),
                ('AccountNo', models.CharField(blank=True, max_length=7, null=True)),
                ('email', models.CharField(blank=True, max_length=122, null=True)),
                ('AccountType', models.CharField(blank=True, max_length=122, null=True)),
                ('Amount', models.CharField(blank=True, max_length=122, null=True)),
            ],
        ),
    ]
