# Generated by Django 3.1.7 on 2021-04-11 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0005_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='Email',
        ),
    ]
