# Generated by Django 3.1.7 on 2021-04-11 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0006_auto_20210411_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Amount',
            new_name='CurrrentBalance',
        ),
    ]
