# Generated by Django 3.1.7 on 2021-04-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0008_auto_20210411_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=122, null=True)),
                ('AccountNo', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
    ]
