# Generated by Django 3.1.7 on 2021-04-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0009_bank_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='CurrentBalance',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
