# Generated by Django 3.1.7 on 2021-04-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0010_auto_20210412_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='CurrentBalance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
