# Generated by Django 3.1.7 on 2021-04-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0012_transfer_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer_money',
            name='Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
