# Generated by Django 3.1.7 on 2021-04-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0013_transfer_money_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_statement',
            name='Date',
            field=models.DateTimeField(blank=True, max_length=7, null=True),
        ),
    ]
